name: Build PULSAR Firmware
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # 서브모듈을 여기서 바로 가져오지 않고 일단 소스만 받습니다.
          fetch-depth: 0

      - name: Run build in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: px4io/px4-dev-nuttx-bionic:2020-04-01
          options: -v ${{ github.workspace }}:/work
          run: |
            cd /work
            git config --global --add safe.directory /work
            
            # 깨진 서브모듈 연결을 강제로 초기화하고 다시 받아옵니다.
            git submodule sync
            git submodule update --init --recursive --force
            
            make distclean
            make px4_fmu-v4_default

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pulsar_pixhawk_firmware
          path: build/px4_fmu-v4_default/px4_fmu-v4_default.px4
